name: Run Tests

on:
  push:
    branches:
      - main  # Runs tests when pushing to 'main' branch
  pull_request:
    branches:
      - main  # Runs tests when creating PRs to 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Test on latest Ubuntu
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # Test on multiple Python versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run Tests
        run: pytest
